### ISSUE TITLE
检测到验证码之后报错，Loc好像没有开启验证码，应该是识别错了

### ISSUE THREAD

**Issue by LangfordKuo** [nodeloc/hostloc_auto#2]
2023-11-02 03:39:04,056 login.py cookies_login：line 143 INFO 初次登录未发现Cookie，使用账号密码登录。
2023-11-02 03:39:04,740 login.py account_login：line 99 ERROR 存在验证码，登陆失败，准备获取验证码中
Traceback (most recent call last):
  File "/root/hostloc_auto/login.py", line 96, in account_login
    if self.account_login_without_verify():
  File "/root/hostloc_auto/login.py", line 75, in account_login_without_verify
    loginhash, formhash = self.form_hash()
  File "/root/hostloc_auto/login.py", line 31, in form_hash
    loginhash = re.search(r'<div id="main_messaqge_(.+?)">', rst).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2023-11-02 03:39:04,894 login.py main：line 178 ERROR 失败，发生了一个错误！
Traceback (most recent call last):
  File "/root/hostloc_auto/login.py", line 164, in main
    self.account_login()
  File "/root/hostloc_auto/login.py", line 101, in account_login
    code = self.verify_code()
  File "/root/hostloc_auto/login.py", line 60, in verify_code
    code = self.verify_code_once()
  File "/root/hostloc_auto/login.py", line 38, in verify_code_once
    update = re.search(r'update=(.+?)&idhash=', rst).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nodeloc** [comment]
可能是hostloc不稳定导致页面没获取到，从而程序认为可能有验证码。但应该并不影响整体使用。
