### ISSUE TITLE
初次运行python3 disucz.py 出现错误

### ISSUE THREAD

**Issue by xzyone** [nodeloc/hostloc_auto#6]
Traceback (most recent call last):
  File "/root/tang/login.py", line 164, in main
    self.account_login()
  File "/root/tang/login.py", line 101, in account_login
    code = self.verify_code()
  File "/root/tang/login.py", line 60, in verify_code
    code = self.verify_code_once()
  File "/root/tang/login.py", line 38, in verify_code_once
    update = re.search(r'update=(.+?)&idhash=', rst).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

branch: 98t

**Comment by nodeloc** [comment]
看下ip是不是被屏蔽了
